### ISSUE TITLE
apagar o README.md do histórico

### ISSUE THREAD

**Issue by tonicospinelli** [EvertonMutti/shared_object#1]
Recentemente participei deste desafio de código e, após o término, fomos liberados de compartilhar o código aqui no GitHub. No entanto, foi solicitado que o enunciado do desafio fosse removido e que o nome da empresa fosse omitido.

Enquanto revisava alguns repositórios no GitHub, notei que alguns ainda contêm o enunciado do desafio dentro da árvore de histórico. Para evitar qualquer problema com a empresa, gostaria de sugerir que você considerasse remover o arquivo contendo o enunciado da árvore histórica do repositório. Isso pode ser feito através deste [guia][1] que demonstra como fazer utilizando comandos de Git, e há tutoriais online que explicam como fazer isso de forma eficaz.

[1]: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository

**Comment by EvertonMutti** [comment]
Obrigado pela atenção Antonio, acabei de fazer a alteração no histórico.
